=== Riverscapes/RiverscapesToolbar/Resources/ProjectSamples/XSD/Project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Project" type="ProjectType"/>

  <!-- =========================================================================

    Common Elements:
      - All projects must have the Following:

  ============================================================================== -->


  <!-- Top Leve item: Here's where the overall project gets Defined -->
  <xs:complexType name="ProjectType">
    <xs:sequence>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="xs:string" name="ProjectType"/>
      <xs:element type="MetaDataType" name="MetaData"/>
      <xs:element type="InputsType" name="Inputs"/>
      <xs:element type="RealizationsType" name="Realizations"/>
      <xs:element type="AnalysesType" name="Analyses" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type"/>
  </xs:complexType>

  <!-- A Project can have realizations -->
  <xs:complexType name="RealizationType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="ParametersType" name="Parameters" minOccurs="0"/>
      <xs:element type="MetaDataType" name="MetaData" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="DateCreated" use="optional"/>
    <xs:attribute type="xs:string" name="ProductVersion" use="optional"/>
    <xs:attribute type="xs:string" name="Guid" use="optional"/>
  </xs:complexType>

  <!--Realizations Must have an Analysis-->
  <xs:complexType name="AnalysisType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="OutputsType" name="Outputs" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- The things that go in the plural containers -->
  <xs:complexType name="MetaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- These are Just Plural Containers for things -->

  <xs:complexType name="MetaDataType">
    <xs:sequence>
      <xs:element type="MetaType" name="Meta" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AnalysesType">
    <xs:sequence>
      <xs:element type="AnalysisType" name="Analysis" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ParametersType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>


  <!-- Let's define our Input/Output Data Types-->
  <xs:complexType name="InputsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="xs:string" name="Value"/>
      <xs:element type="RasterType" name="Raster"/>
      <xs:element type="VectorType" name="Vector"/>
      <xs:element type="DEMType" name="DEM"/>
      <xs:element type="HillShadeType" name="HillShade"/>
    </xs:choice>
  </xs:complexType>

  <!--Outputs Type-->
  <xs:complexType name="OutputsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="xs:string" name="Value"/>
      <xs:element type="RasterType" name="Raster"/>
      <xs:element type="VectorType" name="Vector"/>
      <xs:element type="DEMType" name="DEM"/>
      <xs:element type="HillShadeType" name="HillShade"/>
    </xs:choice>
  </xs:complexType>

  <!-- Now let's define some types -->
  <xs:complexType name="GeoSpatialType">
    <xs:sequence>
      <xs:element type="xs:string" name="Name" minOccurs="0"/>
      <xs:element type="xs:string" name="Path" minOccurs="0"/>
      <xs:element type="xs:string" name="BasePath" minOccurs="0"/>
      <xs:element type="xs:string" name="fileRef" minOccurs="0"/>
      <xs:element type="MetaDataType" name="MetaData" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="Guid"/>
  </xs:complexType>

  <xs:complexType name="RasterType">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="VectorType">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="DEMType">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="HillShadeType">
    <xs:complexContent>
      <xs:extension base="GeoSpatialType"/>
    </xs:complexContent>
  </xs:complexType>



  <xs:complexType name="RealizationsType">
    <xs:choice>
      <xs:element type="DoDType" name="DoD" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="VBETType" name="VBET" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="RiverStylesType" name="RiverStyles" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>

  <!-- =========================================================================

    Project: VBET

  ============================================================================== -->

  <xs:complexType name="VBETType">
    <xs:complexContent>
      <xs:extension base="RealizationType"/>
    </xs:complexContent>
    <xs:sequence>
      <xs:element type="GCDInputType" name="Inputs" minOccurs="0"/>
      <xs:element type="GCDAnalysisType" name="Analysis" minOccurs="0"/>
    </xs:sequence>
    <xs:sequence>

    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VBETType">
    <xs:sequence>
      <xs:element type="ParametersType" name="Parameters" minOccurs="0"/>
      <xs:element type="VBETInputType" name="Inputs" minOccurs="0"/>
      <xs:element type="VBETAnalysisType" name="Analysis" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="VBETInputType">
    <xs:sequence>
      <xs:element type="VBETInputTopographyType" name="Topography"/>
      <xs:element type="VBETInputDrainageType" name="DrainageNetworks"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VBETInputTopographyType">
    <xs:sequence>
      <xs:element type="DEMType" name="DEM" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="DEMType" name="Flow" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="DEMType" name="Slope" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VBETInputDrainageType">
    <xs:sequence>
      <xs:element type="VBETInputDrainageNetworkType" name="Network"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VBETInputDrainageNetworkType">
    <xs:complexContent>
      <xs:extension base="VectorType"/>
      <xs:element type="VBETBufferType" name="Buffers"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="VBETBufferType">
    <xs:sequence>
      <xs:element type="VectorType" name="Buffer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VBETAnalysisType">
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="OutputsType" name="Outputs" minOccurs="0"/>
  </xs:complexType>


  <!-- =========================================================================

    Project: NREI

  ============================================================================== -->


  <!-- =========================================================================

    Project: Confinement

  ============================================================================== -->




  <!-- =========================================================================

    Project: River Styles

  ============================================================================== -->

  <xs:complexType name="RiverStylesType">
    <xs:complexContent>
      <xs:extension base="RealizationType"/>
    </xs:complexContent>
    <xs:sequence>
      <xs:element type="RiverStylesInputType" name="Inputs" minOccurs="0"/>
      <xs:element type="RiverStylesAnalysisType" name="Analysis" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RiverStylesInputType">
    <xs:sequence>
      <xs:element type="RiverStylesInputDrainageNetworksType" name="DrainageNetworks"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RiverStylesInputDrainageNetworksType">
    <xs:sequence>
      <xs:element type="RiverStylesInputDrainageNetworkType" name="Network"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RiverStylesInputDrainageNetworkType">
    <xs:complexContent>
      <xs:extension base="VectorType"/>
      <xs:element type="VBETBufferType" name="Buffers"/>
      <xs:element type="ValleyBottomType" name="ValleyBottom"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ValleyBottomType">
    <xs:complexContent>
      <xs:extension base="VectorType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="RiverStylesConfinementType">
    <xs:sequece>
      <xs:element type="VectorType" name="Confinement"/>
    </xs:sequece>
  </xs:complexType>

  <xs:complexType name="RiverStylesReachType">
    <xs:sequece>
      <xs:element type="ManualCrossChecksType" name="ManualCrossChecks"/>
    </xs:sequece>
  </xs:complexType>

  <xs:complexType name="ManualCrossChecksType">
    <xs:sequece>
      <xs:element type="VectorType" name="ManualCrossCheck"/>
    </xs:sequece>
  </xs:complexType>

  <xs:complexType name="RiverStylesAnalysisType">
    <xs:sequence>
      <xs:element type="RiverStylesConfinementType" name="Confinements"/>
      <xs:element type="RiverStylesReachType" name="RiverStyleReach"/>
    </xs:sequence>
  </xs:complexType>


  <!-- =========================================================================

    Project: GCD

  ============================================================================== -->

  <xs:complexType name="DoDType">
    <xs:complexContent>
      <xs:extension base="RealizationType"/>
    </xs:complexContent>
    <xs:sequence>
      <xs:element type="GCDInputType" name="Inputs" minOccurs="0"/>
      <xs:element type="GCDAnalysisType" name="Analysis" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

    <xs:complexType name="RasterType">

  </xs:complexType>


  <xs:complexType name="GCDInputType">
    <xs:sequence>
      <xs:element type="VBETInputTopographyType" name="Topography"/>
      <xs:element type="VBETInputDrainageType" name="DrainageNetworks"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GCDAnalysisType">
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="OutputsType" name="Outputs"/>
  </xs:complexType>

</xs:schema>

=== Riverscapes/RiverscapesToolbar/Resources/ProjectSamples/GUT.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/V1/Project.xsd">

  <Name>My GUT NAME</Name>
  <ProjectType>GUT</ProjectType>

  <MetaData>
    <Meta Name="year">2012</Meta>
    <Meta Name="visit">1029</Meta>
  </MetaData>

  <!--Inputs are defined here so they can be used in Realizations-->
  <Inputs>
    <DEM id="DEM01" Guid="">
      <Name>DEM1</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/dem.img</Path>
    </DEM>
    <Raster id="DETDEM01" Guid="">
      <Name>Detrended DEM</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/detDEM.img</Path>
    </Raster>
    <Raster id="DEPTH01" Guid="">
      <Name>Water Depth</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/waterDepth.img</Path>
    </Raster>

    <HillShade id="HS01" Guid="">
      <Name>Hillshade</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/HS.img</Path>
    </HillShade>

    <Vector id="BFCL01" Guid="">
      <Name>Bankfull CenterLine</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/bfCL.shp</Path>
    </Vector>
    <Vector id="BFPOLY01" Guid="">
      <Name>Bankfull Polygon</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/bfPolygon.shp</Path>
    </Vector>
    <Vector id="BFXS01" Guid="">
      <Name>Bankfull Cross Sections</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/bfXS.shp</Path>
    </Vector>
    <Vector id="CHUNCLIP01" Guid="">
      <Name>Channel Units Clip</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/channelUnitsClip.shp</Path>
    </Vector>
    <Vector id="THALWEG01" Guid="">
      <Name>Thalweg</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/Thalweg.shp</Path>
    </Vector>
    <Vector id="WEPOLY01" Guid="">
      <Name>Wetted Polygon</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Inputs/wePoly.shp</Path>
    </Vector>


  </Inputs>

  <Realizations>
    <GUT DateCreated="" Guid="" ProductVersion="" Promoted="true">
      <Name>VISIT 1029 Realization 1</Name>

      <Parameters>
        <Param Name=""></Param>
      </Parameters>

      <!--In this case the inputs for this realization reference
      the ones defined at the top of the file. If there are any
      inputs specific to this realization they would be defined
      here instead of referencing them.-->
      <Inputs>
        <Raster ref="DEM01"/>
        <Raster ref="DETDEM01"/>
        <Raster ref="DEPTH01"/>
        <Raster ref="BFCL01"/>
        <Raster ref="BFPOLY01"/>
        <Raster ref="BFXS01"/>
        <Raster ref="CHUNCLIP01"/>
        <Raster ref="THALWEG01"/>
        <Raster ref="WETPOLY01"/>
      </Inputs>

      <Analysis>
        <Outputs>
          <InChannel>
            <Tier1>
              <Path>CBW05583-028079/2012/VISIT_1029/Output/Tier1_InChannel.shp</Path>
            </Tier1>
            <Tier2>
              <Path>CBW05583-028079/2012/VISIT_1029/Output/Tier2_InChannel.shp</Path>
            </Tier2>
            <Tier3>
              <Path>CBW05583-028079/2012/VISIT_1029/Output/Tier3_InChannel.shp</Path>
            </Tier3>
          </InChannel>
          <OutChannel>
            <Tier1>
              <Path>CBW05583-028079/2012/VISIT_1029/Output/Tier1_OutofChannel.shp</Path>
            </Tier1>
            <Tier2>
              <Path>CBW05583-028079/2012/VISIT_1029/Output/Tier2_OutofChannel.shp</Path>
            </Tier2>
            <Tier3>
              <Path>CBW05583-028079/2012/VISIT_1029/Output/Tier3_OutofChannel.shp</Path>
            </Tier3>
          </OutChannel>
        </Outputs>
      </Analysis>

    </GUT>
  </Realizations>
</Project>

=== Riverscapes/RiverscapesToolbar/Resources/ProjectSamples/NREI.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/v1/Project.xsd">

  <Name>CWB_0000001</Name>
  <ProjectType>NREI</ProjectType>

  <MetaData>
    <Meta Name="year">2012</Meta>
    <Meta Name="visit">1029</Meta>
    <Meta Name="flow">Q001</Meta>
  </MetaData>

  <Inputs>
    <Raster id="depth01" Guid="">
      <Name>Depth</Name>
      <Path>CWB_0000001/2012/1029/Q001/inputs/WaterDepth1.tif</Path>
    </Raster>
    <Raster id="velocity01" Guid="">
      <Name>Velocity</Name>
      <Path>CWB_0000001/2012/1029/Q001/inputs/WaterVelocity1.tif</Path>
    </Raster>
  </Inputs>

  <Realizations>
    <NREI Promoted="true" DateCreated="2016-07-08T23:49:51" ProductVersion="1.4.0" Guid="241cdf2a-a397-4fd7-acd2-de0869ed4662">
      <Name>2012 Visit 1029 Flow Q001</Name>
      <Inputs>
        <Raster>
          <Name>Depth</Name>
          <InputRef>depth01</InputRef>
        </Raster>
        <Raster>
          <Name>Velocity</Name>
          <InputRef>velocity01</InputRef>
        </Raster>
      </Inputs>

      <Analysis>
        <Raster>
          <Name>NREI</Name>
          <Path>CWB_0000001/2012/1029/Q001/outputs/Steelhead/70mm/nrei.tif</Path>
        </Raster>
      </Analysis>
    </NREI>
  </Realizations>

</Project>

=== Riverscapes/RiverscapesToolbar/Resources/ProjectSamples/FHM.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/v1/Project.xsd">

  <Name>My GUT NAME</Name>
  <ProjectType>GUT</ProjectType>

  <MetaData>
    <Meta Name="year">2012</Meta>
    <Meta Name="visit">1029</Meta>
  </MetaData>

    <!--Inputs are defined here so they can be used in Realizations-->
  <!-- Inputs must have unique Ids that can be referenced in realizations I'm keeping
    legible here so that it's readable in the realiations the GUID is to keep things unique-->
  <Inputs>
    <Raster id="DEPTH01" Guid="">
      <Name>Hydro Results: Depth</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Q_001/Inputs/HydroResults/Depth.tif</Path>
    </Raster>
    <Raster id="VELOCITY01" Guid="">
      <Name>Hydro Results: Velocity</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Q_001/Inputs/HydroResults/Velocity.tif</Path>
    </Raster>
    <Raster id="GRAINSIZE01" Guid="">
      <Name>Grainsize: D50</Name>
      <Path>CBW05583-028079/2012/VISIT_1029/Q_001/Inputs/GrainSize/D50.tif</Path>
    </Raster>
  </Inputs>

  <Realizations>
    <FHM Guid="" DateCreated="" ProductVersion="" Promoted="true">
      <Name>FHM Realization 01</Name>

      <Parameters>
        <Param Name="Param1">Param</Param>
      </Parameters>

      <Inputs>
        <Raster id="Depth">
          <InputRef>DEPTH01</InputRef>
        </Raster>
        <Raster id="Velocity">
          <InputRef>VELOCITY01</InputRef>
        </Raster>
        <Raster id="GrainSize">
          <InputRef>GRAINSIZE01</InputRef>
        </Raster>
      </Inputs>

      <Analyses>
        <Fuzzy>


        </Fuzzy>
        <HSI>

        </HSI>
      </Analyses>
    </FHM>
  </Realizations>

</Project>

=== Riverscapes/RiverscapesToolbar/Resources/ProjectSamples/NREIsample.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/v1/Project.xsd">

  <Name>CWB_0000001</Name>
  <ProjectType>NREI</ProjectType>

  <MetaData>
    <Meta Name="Year">2012</Meta>
    <Meta Name="Visit">1029</Meta>
    <Meta Name="Flow">Q001</Meta>
  </MetaData>

  <Inputs>
    <Raster id="Depth01" Guid="241cdf2a-a397-4fd7-acd2-de0869ed4662">
      <Name>Depth</Name>
      <Path>CWB_0000001/2012/1029/Q001/inputs/WaterDepth1.tif</Path>
    </Raster>
    <Raster id="Velocity01" Guid="241cdf2a-a397-4fd7-acd2-de0869ed4662">
      <Name>Velocity</Name>
      <Path>CWB_0000001/2012/1029/Q001/inputs/WaterVelocity1.tif</Path>
    </Raster>
  </Inputs>

  <Realizations>
    <Realization DateCreated="2016-07-08T23:49:51" ProductVersion="1.0.0" Guid="241cdf2a-a397-4fd7-acd2-de0869ed4662">

      <Name>Realization: 2012 Visit 1029 Flow Q001</Name>

      <Parameters>
        <Param Name="species">Steelhead</Param>
        <Param Name="size_mm">70</Param>
      </Parameters>

      <Inputs>
        <Raster>
          <InputRef>Depth01</InputRef>
          <MetaData>
            <Meta Name="ProgramLinkage">DEPTH</Meta>
          </MetaData>
        </Raster>
        <Raster>
          <InputRef>Velocity01</InputRef>
          <MetaData>
            <Meta Name="ProgramLinkage">VELOCITY</Meta>
          </MetaData>
        </Raster>
      </Inputs>

      <Analyses>
        <Analysis>
          <Name>My Analysis</Name>
          <Outputs>
            <Raster>
              <Name>NREI</Name>
              <Path>CWB_0000001/2012/1029/Q001/outputs/Steelhead/70mm/nrei.tif</Path>
            </Raster>
          </Outputs>
        </Analysis>
      </Analyses>

    </Realization>


  </Realizations>

</Project>

=== Riverscapes/RiverscapesToolbar/Resources/ProjectSamples/ProjectLinksSCRATCH.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/v1/Project.xsd">

  <Name>Someproject</Name>
  <ProjectType>SomeProject</ProjectType>

    <MetaData>
      <Meta Name="SomeKey">SomeVal</Meta>
    </MetaData>

    <Inputs>

      <!--HERE ARE SOME PROJECT LINK CASES WE NEED TO COVER-->

      <!--Case 1: Local file, non program vallye bottom file-->
      <Vector id="valleybottom01">
        <Name>USal_valley_bottom</Name>
        <Path>inputs\confinements\valley_bottom_polygon\valley_bottom_polygon_01\USal_valleybottom.shp</Path>
      </Vector>

      <!--Case 2: External project, local file not a program-->
      <Vector id="valleybottom01">
        <Name>USal_valley_bottom</Name>
        <ProjectLink>Sample_VBET_Project</ProjectLink>
        <Path>inputs\confinements\valley_bottom_polygon\valley_bottom_polygon_01\USal_valleybottom.shp</Path>
      </Vector>

     <!--Case 3: External program-->
      <VBET id="valleybottom01">
        <RelativePath>s3://something/soemthing/something/VBET/Sample_VBET_Project/vbet3.xml</RelativePath>
        <OutputNodeXPath>//Project/Realizations/VBET[@promoted='TRUE']/Analysis/Outputs/Vector[@id='ValleyBottom']</OutputNodeXPath>
        <OutputNodeGUID>241cdf2a-a397-4fd7-acd2-de0869ed4662</OutputNodeGUID>
      </VBET>




      <!--Context Layers-->
      <Vector id="ecoregions01" Guid="">
        <Name>Eco Regions</Name>
        <Path>analyses\context\layers\UpperSalmon_eco_L4.shp</Path>
      </Vector>
      <Vector id="watershedBoundary01" Guid="">
        <Name>Watershed Boundary</Name>
        <Path>analyses\context\layers\watershed_boundary\Upper_Salmon_ab_Redfish_Boundary.shp</Path>
      </Vector>
      <Vector id="hillshade01" Guid="">
        <Name>Hillshade</Name>
        <Path>analyses\context\layers\hillshade\Upper_Salmon_Hillshade.tif</Path>
      </Vector>
    </Inputs>


    <Realizations>
      <RiverStyles Promoted="1" DateCreated="" ProductVersion="" Guid="241cdf2a-a397-4fd7-acd2-de0869ed4662">
        <Name>USal_confinement_500m</Name>

        <Parameters>
          <Param Name="segmentation_distance">500</Param>
        </Parameters>

        <!--Inputs refer to the files defined at the top of the file-->
        <Inputs>
          <DrainageNetworks GUID="241cdf2a-a397-4fd7-acd2-de0869ed4662">
            <Network>
              <fileRef>drainageNetwork01</fileRef>
              <Buffers>
                <Buffer>
                  <fileRef>USal_500m</fileRef>
                </Buffer>
              </Buffers>
              <ValleyBottom>
                <fileRef>valleybottom01</fileRef>
              </ValleyBottom>
            </Network>
          </DrainageNetworks>
        </Inputs>

        <Analysis>
          <Confinements>
            <Confinement>
              <Name>USal_confinement_500m</Name>
              <Path>analyses\confinements\confinement_01\USal_Confinement_500m.shp</Path>
              <MetaData>
                <Meta Name="segmentation_distance">500</Meta>
              </MetaData>
            </Confinement>
          </Confinements>
          <RiverStyleReach>
            <ManualCrossChecks>
              <ManualCrossCheck>
                <Path>analyses\river_styles\manual_crosschecks\manual_crosscheck_01\USal_River_Styles.shp</Path>
              </ManualCrossCheck>
            </ManualCrossChecks>
          </RiverStyleReach>
        </Analysis>

      </RiverStyles>

    </Realizations>

</Project>

=== Riverscapes/RiverscapesToolbar/Resources/ProjectSamples/test.xml
<?xml version='1.0' encoding='utf-8'?>
<Project Guid="970EA1CB-B628-4EEC-BCF0-96DE592331B1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="XSD/v1/Project.xsd">
  <Name>Sample V-BET Project</Name>
  <ProjectType>V-BET</ProjectType>
  <MetaData>
    <Meta Name="HUC8ID">17060107</Meta>
    <Meta Name="HUC8NAME">Lower Snake-Tucannon</Meta>
  </MetaData>
  <Inputs>
    <Raster id="DEM001">
      <Name>DEM</Name>
      <fileRef>01_Inputs/01_Topo/DEM_001/Goose_Raft_DEM_10m.tif</fileRef>
    </Raster>
    <Vector id="Network001">
      <Name>Network</Name>
      <Path>01_Inputs/02_Network/Network_001/NHD_Goose_Perennial.shp</Path>
    </Vector>
  </Inputs>
  <Realizations>
    <VBET DateCreated="2016-11-08T10:36:47" Guid="F9734569-A0CA-4860-9BE0-7D01624449F7" ProductVersion="0.1">
      <Name>VBET realization 1</Name>
      <Parameters>
        <Param Name="lg_buf">500</Param>
        <Param Name="med_buf">150</Param>
        <Param Name="sm_buf">25</Param>
      </Parameters>
      <Inputs>
        <Input>
          <Name>DEM</Name>
          <Path />
          <fileRef>DEM001</fileRef>
        </Input>
        <Input>
          <Name>Network</Name>
          <Path />
          <fileRef>Network001</fileRef>
        </Input>
      </Inputs>
      <Analysis>
        <Outputs>
        <Output>
          <Valley Bottom>
            <Path>02_Analyses/Output_001/Tucannon_VBET_edited.shp</Path>
          </Valley Bottom>
        </Output>
        </Outputs>
      </Analysis>
    </VBET>
  </Realizations>
</Project>
