=== Riverscapes/RiverscapesToolbar/XML/XSD/project_explorer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Documentation -->
  <xs:annotation>
    <xs:appinfo>Whiz thing</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines a tree that is used by the various tools out there.
    </xs:documentation>
  </xs:annotation>
  
  
  <!-- Overall Structure  -->
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Name"/>
        <xs:element type="xs:string" name="Description" minOccurs="0"/>
        <xs:element type="xs:string" name="ProjectType"/>
        <xs:element type="NodeType" name="Node"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!-- Node: A one-off tree branch that has an xpath -->
  <xs:complexType name="NodeType">
      <xs:sequence>
        <xs:element name="Label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="xpath"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Type" minOccurs="0"/>
        <xs:element ref="Entity" minOccurs="0"/>
        <xs:element name="Children" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element type="NodeType" name="Node" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element type="RepeaterType" name="Repeater" minOccurs="1" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attribute type="xs:string" name="collapsed"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
  </xs:complexType>

  <!-- Repeaters: loop over xml node "arrays" -->
  <xs:complexType name="RepeaterType">
      <xs:sequence>
        <xs:element name="Label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="xpath"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="Xpath"/>
        <xs:choice>
          <xs:element type="NodeType" name="Node" maxOccurs="1"/>
          <xs:element type="RepeaterType" name="Repeater" maxOccurs="1"/>
        </xs:choice>
      </xs:sequence>
  </xs:complexType>

  <!--Entities are the leaves of the tree-->
  <xs:element name="Entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Type"/>
        <xs:choice>
          <xs:element type="xs:string" name="Xpath"/>
          <xs:element type="xs:string" name="Tileservice"/>
        </xs:choice>
        <xs:element type="xs:string" name="Label" minOccurs="0"/>
        <xs:element type="xs:string" name="Symbology" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Riverscapes/RiverscapesToolbar/XML/ec.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="XSD/project_explorer.xsd">
    <Name>Electrical Conductivity</Name>
    <ProjectType>EC</ProjectType>
    <Node xpathlabel="Name">
        <Children>
            <Repeater label="Realizations" xpath="Realizations/EC">
                <!-- this is a template for how each realization should render-->
                <Node xpathlabel="Name">
                    <Children collapsed="false">
                        <Node label="Inputs" xpath="Inputs">
                            <Children>
                                <Node xpathlabel="Name" xpath="Vector[@id='CATCH_POLY']" type="vector" symbology="input_catchmentarea"/>
                                <Node xpathlabel="Name" xpath="Vector[@id='STRM_LINE']" type="vector" symbology="input_streamnetwork"/>
                            </Children>
                        </Node>
                        <Node label="Analyses" xpath="Analyses">
                            <Children>
                                <Node label="Outputs" xpath="Analysis/Outputs">
                                    <Children>
                                        <Node xpathlabel="Name" xpath="Vector" type="vector" symbology="Conductivity"/>
                                    </Children>
                                </Node>
                            </Children>
                        </Node>
                    </Children>
                </Node>
            </Repeater>
        </Children>
    </Node>
</Project>

=== Riverscapes/RiverscapesToolbar/XML/gpp.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="XSD/project_explorer.xsd">
    <Name>RVD</Name>
    <ProjectType>GPP</ProjectType>
    <Node xpathlabel="Name">
        <Children>
            <Repeater label="Realizations" xpath="Realizations/GPP">
                <!-- this is a template for how each realization should render-->
                <Node xpathlabel="Name">
                    <Children collapsed="false">
                        <Node label="Conductivity" xpath="Inputs/Vector[@ref='cond1']" type="vector" symbology="Conductivity"/>
                        <Node label="Solar" xpath="Inputs/Vector[@ref='solar1']" type="vector" symbology="Solar_Vector"/>
                        <Node label="Temperature" xpath="Inputs/TemperatureModel" type="vector" symbology="StreamTemp"/>
                        <Repeater label="Analysis" xpath="Analyses/Analysis/Outputs/Vector">
                            <Node xpathlabel="Name" xpath="Vector" type="vector" symbology="GPP_Prediction"/>
                        </Repeater>
                    </Children>
                </Node>
            </Repeater>
        </Children>
    </Node>
</Project>

=== Riverscapes/RiverscapesToolbar/XML/vbet.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="XSD/project_explorer.xsd">
  <Name>VBET</Name>
  <ProjectType>VBET</ProjectType>
  <Inputs>
    <Label>Inputs</Label>
    <!--How we render inputs goes here-->
  </Inputs>
  <!--This is a template for how each realization should render-->
  <Realization>
      <Label xpath="Name"/>
      <Children collapsed="false">
        <Node>
          <Label>Inputs</Label>
        </Node>
        <Node>
          <Label>Analyses</Label>
          <Children>
            <Repeater>
              <Label>Output</Label>
              <Xpath>/analyses/output</Xpath>
              <Node>
                <Label xpath="name"></Label>
                <Type>valley bottom</Type>
                <Entity>
                  <Type>vector</Type>
                  <Xpath>filepath</Xpath>
                </Entity>
              </Node>
            </Repeater>
          </Children>
        </Node>
      </Children>
  </Realization>


</Project>

=== Riverscapes/RiverscapesToolbar/XML/solar.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="XSD/project_explorer.xsd">
    <Name>Solar Insolation</Name>
    <ProjectType>Solar</ProjectType>
    <Node xpathlabel="Name">
        <Children>
            <Repeater label="Realizations" xpath="Realizations/Solar">
                <!-- this is a template for how each realization should render-->
                <Node xpathlabel="Name">
                    <Children collapsed="false">
                        <Node label="Inputs" xpath="Inputs">
                            <Children>
                                <Node xpathlabel="Name" xpath="Raster[1]" type="raster" symbology="DEM"/>
                                <Node xpathlabel="Name" xpath="Raster[2]" type="raster" symbology="input_vegheight"/>
                                <Node xpathlabel="Name" xpath="Vector[1]" type="vector" symbology="input_streamnetwork"/>
                                <Node xpathlabel="Name" xpath="Vector[2]" type="vector" symbology="input_streamarea"/>
                            </Children>
                        </Node>
                        <Node label="Analyses" xpath="Analyses">
                            <Children>
                                <Node label="Outputs" xpath="Analysis/Outputs">
                                    <Children>
                                        <Node label="Predicted Solar Insolation Raster" xpath="Raster" type="raster" symbology="Solar_Raster"/>
                                        <Node label="Predicted Solar Insolation Vector" xpath="Vector" type="vector" symbology="Solar_Vector"/>
                                    </Children>
                                </Node>
                            </Children>
                        </Node>
                    </Children>
                </Node>
            </Repeater>
        </Children>
    </Node>
</Project>
