=== Riverscapes/RiverscapesToolbar/Resources/XML/project_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Documentation -->
  <xs:annotation>
    <xs:appinfo>Whiz thing</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines a tree that is used by the various tools out there.
    </xs:documentation>
  </xs:annotation>
  
  
  <!-- Overall Structure  -->
  <xs:element name="project">
    <xs:annotation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="name"/>
        <xs:element type="xs:string" name="description" minOccurs="0"/>
        <xs:element type="xs:string" name="test"/>
        <!-- First node here -->
        <xs:element ref="node"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Node Schema Definition -->
  <xs:element name="node">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="xpath"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="type" minOccurs="0"/>
        <xs:element ref="entity" minOccurs="0"/>
        <xs:element name="children" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element ref="node" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element ref="repeater" minOccurs="1" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attribute type="xs:string" name="collapsed"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Repeater -->
  <xs:element name="repeater">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="xpath"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="xpath"/>
        <xs:choice>
          <xs:element ref="node" maxOccurs="1"/>
          <xs:element ref="repeater" maxOccurs="1"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- Entities -->
  <xs:element name="entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="type"/>
        <xs:choice>
          <xs:element type="xs:string" name="xpath"/>
          <xs:element type="xs:string" name="tileservice"/>
        </xs:choice>
        <xs:element type="xs:string" name="label" minOccurs="0"/>
        <xs:element type="xs:string" name="symbology" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Riverscapes/RiverscapesToolbar/XML/hs_project.xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="project_schema.xsd">
  <name>GCD</name>
  <test>/SystemInfo</test>
  <node>
    <label>Habitat</label>
    <children collapsed="false">
      <repeater>
        <label>Prepared Inputs</label>
        <xpath>SimulationHSCInputs</xpath>
        <node>
          <label xpath="HSPreparedPath"/>
          <entity>
            <type>raster</type>
            <xpath>HSPreparedPath</xpath>
            <symbology>DEM</symbology>
          </entity>
        </node>
      </repeater>
      <repeater>
        <label>Simulations</label>
        <xpath>Simulations</xpath>
        <node>
          <label xpath="Title"/>
          <children>
            <node>
              <label>Output Raster</label>
              <entity>
                <type>raster</type>
                <xpath>OutputRaster</xpath>
                <symbology>DEM</symbology>
              </entity>
            </node>
          </children>
        </node>
      </repeater>
      <node>
        <label>Context Layers</label>
        <children>
          <node>
            <label>Google Maps</label>
            <entity>
              <type>tiles</type>
              <tileservice>GMaps</tileservice>
            </entity>
          </node>
          <node>
            <label>NAIP</label>
            <entity>
              <type>tiles</type>
              <tileservice>NAIP</tileservice>
            </entity>
          </node>
        </children>
      </node>
    </children>
  </node>
</project>

=== Riverscapes/RiverscapesToolbar/XML/sample_project.xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="project_schema.xsd">
  <name>Sample</name>
  <test>/sampleName</test>
  <node>
    <label xpath="sampleName"/>
    <children collapsed="false">
      <repeater>
        <label>Inputs</label>
        <xpath>/inputs/input</xpath>
        <node>
          <label xpath="name"/>
          <type>SOME_TYPE</type>
          <entity>
            <type>raster</type>
            <xpath>filepath</xpath>
            <symbology>DEM</symbology>
          </entity>
        </node>
      </repeater>
      <repeater>
        <label>Outputs</label>
        <xpath>/outputs/output</xpath>
        <node>
          <label xpath="name"/>
          <type>SOME_TYPE</type>
          <entity>
            <type>raster</type>
            <xpath>filepath</xpath>
            <symbology>DEM</symbology>
          </entity>
        </node>
      </repeater>
    </children>
  </node>
</project>

=== Riverscapes/RiverscapesToolbar/Resources/XML/vbet_project.xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="project_schema.xsd">
  <name>V-BET</name>
  <test>/Name</test>
  <node>
    <label xpath="Name"/>
    <children collapsed="false">
      <node>
        <label>Inputs</label>
        <children>
          <repeater>
            <label>Topography</label>
            <xpath>/inputs/topography/DEM</xpath>
            <node>
              <label xpath="name"></label>
              <type>DEM</type>
              <entity>
                <type>raster</type>
                <xpath>filepath</xpath>
              </entity>
              <children>
                <repeater>
                  <label>Flow Accumulation</label>
                  <xpath>/inputs/topography/DEM/Flows</xpath>
                  <node>
                    <label xpath="name"></label>
                    <type>flow accumulation</type>
                    <entity>
                      <type>raster</type>
                      <xpath>filepath</xpath>
                    </entity>
                  </node>
                </repeater>
                <repeater>
                  <label>Slope</label>
                  <xpath>/inputs/topography/DEM/Slope</xpath>
                  <node>
                    <label xpath="name"></label>
                    <type>slope</type>
                    <entity>
                      <type>raster</type>
                      <xpath>filepath</xpath>
                    </entity>
                  </node>
                </repeater>
              </children>
            </node>
          </repeater>
          <repeater>
            <label>Network</label>
            <xpath>/inputs/drainage_network/network</xpath>
            <node>
              <label xpath="name"></label>
              <type>network</type>
              <entity>
                <type>vector</type>
                <xpath>filepath</xpath>
              </entity>
              <children>
                <repeater>
                  <label>Buffers</label>
                  <xpath>inputs/drainage_network/network/buffers</xpath>
                  <node>
                    <label xpath="name"></label>
                    <type>buffers</type>
                    <entity>
                      <type>vector</type>
                      <xpath>filepath</xpath>
                    </entity>
                  </node>
                </repeater>
              </children>
            </node>
          </repeater>
        </children>
      </node>
      <node>
        <label>Analyses</label>
        <children>
          <repeater>
            <label>Output</label>
            <xpath>/analyses/output</xpath>
            <node>
              <label xpath="name"></label>
              <type>valley bottom</type>
              <entity>
                <type>vector</type>
                <xpath>filepath</xpath>
              </entity>
            </node>
          </repeater>
        </children>
      </node>
    </children>
  </node>
</project>

=== Riverscapes/RiverscapesToolbar/Resources/XML/gcd_project.xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="project_schema.xsd">
  <name>GCD</name>
  <test>/Project/DEMSurvey</test>
  <node>
    <label>GCD</label>
    <children collapsed="false">
      <node>
        <label>Input</label>
        <children>
          <repeater>
            <label>DEM Surveys</label>
            <xpath>/Project/DEMSurvey</xpath>
            <node>
              <label xpath="Name"/>
              <children collapsed="true">
                <repeater>
                  <label>Associated Surfaces</label>
                  <xpath>AssociatedSurface</xpath>
                  <node>
                    <label xpath="Name"/>
                    <type>ASS_SRF</type>
                    <entity>
                      <type>raster</type>
                      <xpath>Source</xpath>
                      <symbology>BlueToRed</symbology>
                    </entity>
                  </node>
                </repeater>
                <repeater>
                  <label>Error Surfaces</label>
                  <xpath>ErrorSurface</xpath>
                  <node>
                    <label xpath="Name"/>
                    <type>ERR_SRF</type>
                    <entity>
                      <type>raster</type>
                      <xpath>Source</xpath>
                      <symbology>DEM</symbology>
                    </entity>
                  </node>
                </repeater>
                <node>
                  <label xpath="Name"/>
                  <type>DEM</type>
                  <entity>
                    <type>raster</type>
                    <xpath>Source</xpath>
                    <symbology>DEM</symbology>
                  </entity>
                </node>
              </children>
            </node>
          </repeater>
          <node>
            <label>Areas of Interest</label>
          </node>
        </children>
      </node>
      <node>
        <label>Analyses</label>
        <children>
          <repeater>
            <label>Change Detection</label>
            <xpath>/Project/DoDs</xpath>
            <node>
              <label xpath="Name"/>
              <children>
                <node>
                  <label>Thresholded</label>
                  <entity>
                    <type>raster</type>
                    <xpath>ThreshDoDPath</xpath>
                    <symbology>DoD</symbology>
                  </entity>                  
                </node>
              </children>
            </node>
          </repeater>
        </children>
      </node>
      <node>
        <label>Context Layers</label>
        <children>
          <node>
            <label>Google Maps</label>
            <entity>
              <type>tiles</type>
              <tileservice>GMaps</tileservice>
            </entity>
          </node>
          <node>
            <label>NAIP</label>
            <entity>
              <type>tiles</type>
              <tileservice>NAIP</tileservice>
            </entity>
          </node>
        </children>
      </node>
    </children>
  </node>
</project>
