=== Riverscapes/RiverscapesToolbar/Resources/XML/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Documentation -->
  <xs:annotation>
    <xs:appinfo>Whiz thing</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines a tree that is used by the various tools out there.
    </xs:documentation>
  </xs:annotation>
  
  
  <!-- Overall Structure  -->
  <xs:element name="tree">
    <xs:annotation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="node"/>
        <xs:element name="symbologies">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="symbology" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Node Schema Definition -->
  <xs:element name="node">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="xpath"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="type" minOccurs="0"/>
        <xs:element ref="entity" minOccurs="0"/>
        <xs:element name="children" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element ref="node" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element ref="repeater" minOccurs="1" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attribute type="xs:string" name="collapsed"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Repeater -->
  <xs:element name="repeater">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="xpath"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="xpath"/>
        <xs:choice>
          <xs:element ref="node" maxOccurs="1"/>
          <xs:element ref="repeater" maxOccurs="1"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- Entities -->
  <xs:element name="entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="type"/>
        <xs:element type="xs:string" name="xpath"/>
        <xs:element type="xs:string" name="label" minOccurs="0"/>
        <xs:element type="xs:string" name="symbology" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!-- Symbology -->
  <xs:element name="symbology">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ramp"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id" use="optional"/>
    </xs:complexType>
  </xs:element>


  <!-- ramps -->
  <xs:element name="ramp">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="startcolour"/>
        <xs:element type="xs:string" name="endcolour"/>
        <xs:element type="xs:string" name="type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


</xs:schema>

=== Riverscapes/RiverscapesToolbar/Resources/XML/gcd_tree.xml
<?xml version="1.0" encoding="utf-8"?>
<tree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="tree http://releases.northarrowresearch.com/GCD/schema/V1/schema.xsd"
  xsi:noNamespaceSchemaLocation="schema.xsd">
  <node>
    <label>GCD</label>
    <children collapsed="false">
      <node>
        <label>Input</label>
        <children>
          <repeater>
            <label>DEM Surveys</label>
            <xpath>/Project/DEMSurvey</xpath>
            <node>
              <label xpath="Name"/>
              <children collapsed="true">
                <repeater>
                  <label>Associated Surfaces</label>
                  <xpath>AssociatedSurface</xpath>
                  <node>
                    <label xpath="Name"/>
                    <type>ASS_SRF</type>
                    <entity>
                      <type>raster</type>
                      <xpath>Source</xpath>
                      <symbology>BlueToRed</symbology>
                    </entity>
                  </node>
                </repeater>
                <repeater>
                  <label>Error Surfaces</label>
                  <xpath>ErrorSurface</xpath>
                  <node>
                    <label xpath="Name"/>
                    <type>ERR_SRF</type>
                    <entity>
                      <type>raster</type>
                      <xpath>Source</xpath>
                      <symbology>DEM</symbology>
                    </entity>
                  </node>
                </repeater>
                <node>
                  <label xpath="Name"/>
                  <type>DEM</type>
                  <entity>
                    <type>raster</type>
                    <xpath>Source</xpath>
                    <symbology>DEM</symbology>
                  </entity>
                </node>
              </children>
            </node>
          </repeater>
          <node>
            <label>Areas of Interest</label>
          </node>
        </children>
      </node>
      <node>
        <label>Analyses</label>
        <children>
          <repeater>
            <label>Change Detection</label>
            <xpath>/Project/DoDs</xpath>
            <node>
              <label xpath="Name"/>
              <children>
                <node>
                  <label>Thresholded</label>
                  <entity>
                    <type>raster</type>
                    <xpath>ThreshDoDPath</xpath>
                    <symbology>DoD</symbology>
                  </entity>                  
                </node>
              </children>
            </node>
          </repeater>
        </children>
      </node>
    </children>
  </node>


  <symbologies>
    <symbology id="BlueToRed">
      <ramp>
        <startcolour>blue</startcolour>
        <endcolour>red</endcolour>
        <type>stretch</type>
      </ramp>
    </symbology>
    <symbology id="RedToGreen">
      <ramp>
        <startcolour>red</startcolour>
        <endcolour>green</endcolour>
        <type>stretch</type>
      </ramp>
    </symbology>
  </symbologies>

</tree>
